# C_setup_rest — seats 3..10 of C_setup10, for resuming a stranded run.
#
# KNOWN BLOCKED, same cause as C_setup10 (see the note at the top of that
# file): during SETUP the "Before the first night" checklist raises itself
# over the seat sheet whenever an assignment introduces a NEW requirement row
# — the Imp adds "Demon: 1 in bag, expected 1" — so that seat's `back` closes
# the checklist and the seat sheet stays open ("no node matches '^Seat 7,'").
# It does not happen on every seat, so no fixed run of `back`s is right for
# all eight. Not caused by the wave-2 shell inset change.
STEPS = [('tap', '^Seat 3,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Mayor'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'If only 3 players live'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 4,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Saint'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'If you die by execution, your team loses'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 5,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Poisoner'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'they are poisoned tonight and tomorrow'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 6,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Imp'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'If you kill yourself'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 7,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Washerwoman'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'particular Townsfolk'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 8,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Librarian'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'particular Outsider'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 9,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Chef'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'how many pairs of evil players'), ('sleep', 1.2), ('back', None), ('sleep', 1.0), ('tap', '^Seat 10,'), ('wait', 'Change'), ('tap', 'Change…'), ('wait', 'Search characters'), ('tap', 'Search characters'), ('type', 'Empath'), ('sleep', 0.9), ('back', None), ('sleep', 0.6), ('tap', 'how many of your 2 alive neighbors'), ('sleep', 1.2), ('back', None), ('sleep', 1.0)]
